name: Continuous Integration

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.set-key.outputs.key }}
    steps:
      - name: Set cache key
        id: set-key
        run: echo "key=${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}" >> "$GITHUB_OUTPUT"

  lint:
    name: Code Quality & Linting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ needs.setup.outputs.cache-key }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Run Black
        run: black --check --diff .

      - name: Run isort
        run: isort --check-only --diff .

      - name: Run flake8
        run: flake8

      - name: Run mypy
        run: mypy src/

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ needs.setup.outputs.cache-key }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -e ".[test]"

      - name: Run tests
        run: pytest
        env:
          PYTHONPATH: .

      - name: Generate coverage report
        run: pytest --cov --cov-report=xml --cov-report=term
        if: matrix.python-version == '3.11'  # Only generate coverage on latest version

      - uses: actions/upload-artifact@v3
        if: matrix.python-version == '3.11'
        with:
          name: coverage-report
          path: coverage.xml

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [lint, unit-tests]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"  # Use latest stable for integration tests
          cache: 'pip'

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ needs.setup.outputs.cache-key }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -e ".[test]"

      - name: Validate OPENAI_API_KEY
        run: |
          if [ -z "$OPENAI_API_KEY" ]; then
            echo "OPENAI_API_KEY is not set"
            exit 1
          else
            echo "OPENAI_API_KEY is set"
          fi
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Generate test documents
        run: python -m src.test_data_generator
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PYTHONPATH: .

      - name: Run verification
        run: python -m src.run_and_verify
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PYTHONPATH: .

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-documents-${{ github.run_number }}
          path: test_documents/

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: verification-logs-${{ github.run_number }}
          path: test_documents/manifest.json

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -e ".[security]"

      - name: Run safety check
        run: safety check --exit-code
        continue-on-error: false  # Fail on security vulnerabilities

      - name: Run bandit security scan
        run: bandit -r src/ -f json -o bandit-report.json
        continue-on-error: true  # Don't fail build on bandit issues initially

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: security-reports
          path: bandit-report.json

  build-summary:
    name: Build Summary
    runs-on: ubuntu-latest
    needs: [lint, unit-tests, integration-tests, security-scan]
    if: always()

    steps:
      - name: Summarize build
        run: |
          echo "Build Summary:"
          echo "Lint: ${{ needs.lint.result }}"
          echo "Unit Tests: ${{ needs.unit-tests.result }}"
          echo "Integration Tests: ${{ needs.integration-tests.result }}"
          echo "Security Scan: ${{ needs.security-scan.result }}"

          if [[ "${{ needs.lint.result }}" == "failure" || "${{ needs.unit-tests.result }}" == "failure" ]]; then
            echo "❌ Critical jobs failed"
            exit 1
          elif [[ "${{ needs.integration-tests.result }}" == "failure" ]]; then
            echo "⚠️  Integration tests failed - check AI API connectivity"
            exit 1
          else
            echo "✅ All critical jobs passed"
            if [[ "${{ needs.security-scan.result }}" == "failure" ]]; then
              echo "⚠️  Security scan found issues - review artifacts"
            fi
          fi