name: Continuous Integration

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.set-key.outputs.key }}
    steps:
      - name: Set cache key
        id: set-key
        run: echo "key=${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}" >> "$GITHUB_OUTPUT"

  lint:
    name: Code Quality & Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pip'

      - name: Install linters
        run: |
          pip install --upgrade pip
          pip install black flake8 mypy isort

      - name: Run Black
        run: black --check --diff src/ tests/

      - name: Run isort
        run: isort --check-only --diff src/ tests/

      - name: Run flake8
        run: flake8 src/ tests/ --max-line-length=88 --extend-ignore=E203,W503

      - name: Run mypy
        run: mypy src/ --ignore-missing-imports
        continue-on-error: true

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pip'

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ needs.setup.outputs.cache-key }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install test dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt Faker python-docx pytest coverage pytest-cov

      - name: Run tests
        run: python -m pytest tests/ -v --tb=short
        env:
          PYTHONPATH: .

      - name: Generate coverage report
        run: python -m pytest tests/ --cov=src --cov-report=xml --cov-report=term
        continue-on-error: true

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: coverage-report
          path: coverage.xml

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [lint, unit-tests]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pip'

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ needs.setup.outputs.cache-key }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt Faker python-docx

      - name: Validate OPENAI_API_KEY
        run: |
          if [ -z "$OPENAI_API_KEY" ]; then
            echo "OPENAI_API_KEY is not set"
            exit 1
          else
            echo "OPENAI_API_KEY is set"
          fi
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Generate test documents
        run: python -m src.test_data_generator
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PYTHONPATH: .

      - name: Run verification
        run: python -m src.run_and_verify
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PYTHONPATH: .

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-documents-${{ github.run_number }}
          path: test_documents/

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: verification-logs-${{ github.run_number }}
          path: test_documents/manifest.json

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install tools
        run: |
          pip install --upgrade pip
          pip install safety bandit

      - name: Run safety
        run: |
          pip install -r requirements.txt
          safety check --json
        continue-on-error: true

      - name: Run bandit
        run: bandit -r src/ -f json
        continue-on-error: true

  build-summary:
    name: Build Summary
    runs-on: ubuntu-latest
    needs: [lint, unit-tests, integration-tests, security-scan]
    if: always()

    steps:
      - name: Summarize build
        run: |
          echo "Build Summary:"
          echo "Lint: ${{ needs.lint.result }}"
          echo "Unit Tests: ${{ needs.unit-tests.result }}"
          echo "Integration Tests: ${{ needs.integration-tests.result }}"
          echo "Security Scan: ${{ needs.security-scan.result }}"

          if [[ "${{ needs.lint.result }}" == "failure" || "${{ needs.unit-tests.result }}" == "failure" || "${{ needs.integration-tests.result }}" == "failure" ]]; then
            echo "❌ Build failed"
            exit 1
          else
            echo "✅ All critical jobs passed"
          fi